//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from FormulaGrammer.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="FormulaGrammerParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface IFormulaGrammerListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaGrammerParser.formula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFormula([NotNull] FormulaGrammerParser.FormulaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaGrammerParser.formula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFormula([NotNull] FormulaGrammerParser.FormulaContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaGrammerParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] FormulaGrammerParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaGrammerParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] FormulaGrammerParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaGrammerParser.multiplyingExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiplyingExpression([NotNull] FormulaGrammerParser.MultiplyingExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaGrammerParser.multiplyingExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiplyingExpression([NotNull] FormulaGrammerParser.MultiplyingExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaGrammerParser.powExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPowExpression([NotNull] FormulaGrammerParser.PowExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaGrammerParser.powExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPowExpression([NotNull] FormulaGrammerParser.PowExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>PlusAtom</c>
	/// labeled alternative in <see cref="FormulaGrammerParser.signedAtom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPlusAtom([NotNull] FormulaGrammerParser.PlusAtomContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>PlusAtom</c>
	/// labeled alternative in <see cref="FormulaGrammerParser.signedAtom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPlusAtom([NotNull] FormulaGrammerParser.PlusAtomContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>NegativeAtom</c>
	/// labeled alternative in <see cref="FormulaGrammerParser.signedAtom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNegativeAtom([NotNull] FormulaGrammerParser.NegativeAtomContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>NegativeAtom</c>
	/// labeled alternative in <see cref="FormulaGrammerParser.signedAtom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNegativeAtom([NotNull] FormulaGrammerParser.NegativeAtomContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Function</c>
	/// labeled alternative in <see cref="FormulaGrammerParser.signedAtom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction([NotNull] FormulaGrammerParser.FunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Function</c>
	/// labeled alternative in <see cref="FormulaGrammerParser.signedAtom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction([NotNull] FormulaGrammerParser.FunctionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>UnsignedAtom</c>
	/// labeled alternative in <see cref="FormulaGrammerParser.signedAtom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnsignedAtom([NotNull] FormulaGrammerParser.UnsignedAtomContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>UnsignedAtom</c>
	/// labeled alternative in <see cref="FormulaGrammerParser.signedAtom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnsignedAtom([NotNull] FormulaGrammerParser.UnsignedAtomContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaGrammerParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtom([NotNull] FormulaGrammerParser.AtomContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaGrammerParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtom([NotNull] FormulaGrammerParser.AtomContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ScientificNumber</c>
	/// labeled alternative in <see cref="FormulaGrammerParser.scientific"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterScientificNumber([NotNull] FormulaGrammerParser.ScientificNumberContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ScientificNumber</c>
	/// labeled alternative in <see cref="FormulaGrammerParser.scientific"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitScientificNumber([NotNull] FormulaGrammerParser.ScientificNumberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaGrammerParser.func"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunc([NotNull] FormulaGrammerParser.FuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaGrammerParser.func"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunc([NotNull] FormulaGrammerParser.FuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaGrammerParser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariable([NotNull] FormulaGrammerParser.VariableContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaGrammerParser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariable([NotNull] FormulaGrammerParser.VariableContext context);
}
